[tool.poetry]
name = "vembrane"
version = "0.1.0"
description = "Filter VCF/BCF files with simple Python expressions."
authors = ["Till Hartmann"]

[tool.poetry.scripts]
snakefmt = 'vembrane.vembrane:main'

[tool.poetry.dependencies]
python = "^3.7"
pysam = "^0.16"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
